PolovniAutomobili-proba/PolovniAutomobili-proba/Controllers/AutomobiliController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualStudio.Web.CodeGeneration.Utils;
using MongoDB.Bson;
using MongoDB.Driver;
using PolovniAutomobili_proba.Areas.Identity.Data;
using PolovniAutomobili_proba.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PolovniAutomobili_proba.Controllers
{
    public class AutomobiliController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public AutomobiliController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        // GET: AutomobiliController
        public ActionResult Index()
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");

            List<Automobil> automobili = new List<Automobil>();
            foreach (Automobil a in collection.Find(new BsonDocument()).ToList())
            {
                automobili.Add(a);
            }

            IndexAutomobiliViewModel model = new IndexAutomobiliViewModel
            {
                Automobili = automobili
            };

            return View(model);
        }

        // GET: AutomobiliController/Details/5
        public ActionResult Details(string id)
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");

            ObjectId objId = ObjectId.Parse(id);

            var filter = Builders<Automobil>.Filter.Eq("_id", objId);
            var document = collection.Find(filter).First();

            return View(document);
        }

        // GET: AutomobiliController/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: AutomobiliController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Automobil auto)
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");
            //var user = _userManager.GetUserAsync(User).Result;


            Automobil automobil = new Automobil
            {
                Marka = auto.Marka,
                Model = auto.Model,
                Lokacija = auto.Lokacija,
                Cena = auto.Cena,
                Godiste = auto.Godiste,
                Oznake = auto.Oznake,
                Korisnik = _userManager.GetUserAsync(User).Result
            };

            collection.InsertOne(automobil);

            return RedirectToAction("Index");
        }


        [Authorize]
        public ActionResult MojiOglasi()
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");
            //var usersCollection = db.GetCollection<ApplicationUser>("Users");

            var userId = _userManager.GetUserAsync(User).Result.Id;

            var filter = Builders<Automobil>.Filter.Eq("Korisnik._id", userId);

            List<Automobil> model = new List<Automobil>();
            foreach (Automobil a in collection.Find(filter).ToCursor().ToEnumerable())
            {
                model.Add(a);
            }

            return View(model);
        }


        // GET: AutomobiliController/Edit/5
        [Authorize]
        public ActionResult Edit(string id)
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");

            ObjectId objId = ObjectId.Parse(id);

            var filter = Builders<Automobil>.Filter.Eq("_id", objId);
            var document = collection.Find(filter).First();


            EditAutomobilViewModel viewModel = new EditAutomobilViewModel
            {
                Automobil = document,
                AutoId = document.Id.ToString(),
                UserId = document.Korisnik.Id.ToString()
            };
            return View(viewModel);
        }

        // POST: AutomobiliController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditAutomobilViewModel viewModel)
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");

            ObjectId autoId = ObjectId.Parse(viewModel.AutoId);
            ObjectId userId = ObjectId.Parse(viewModel.UserId);

            //var filterBuilder = Builders<Automobil>.Filter;
            //var filter = filterBuilder.Eq("Marka", auto.Marka) & filterBuilder.Eq("Model", auto.Model) & filterBuilder.Eq("Lokacija", auto.Lokacija) 
            //                                                   & filterBuilder.Eq("Cena", auto.Cena) & filterBuilder.Eq("Godiste", auto.Godiste) 
            //                                                   & filterBuilder.Eq("Oznake", auto.Oznake) & filterBuilder.Eq("Korisnik._id", userId);

            var filter = Builders<Automobil>.Filter.Eq("_id", autoId);
            var update = Builders<Automobil>.Update.Set("Marka", viewModel.Automobil.Marka)
                                                   .Set("Model", viewModel.Automobil.Model)
                                                   .Set("Lokacija", viewModel.Automobil.Lokacija)
                                                   .Set("Cena", viewModel.Automobil.Cena)
                                                   .Set("Godiste", viewModel.Automobil.Godiste)
                                                   .Set("Oznake", viewModel.Automobil.Oznake);
            collection.UpdateOne(filter, update);

            return RedirectToAction("MojiOglasi");
        }

        // GET: AutomobiliController/Delete/5
        [Authorize]
        public ActionResult Delete(string id)
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");

            var objectId = ObjectId.Parse(id);

            var filter1 = Builders<Automobil>.Filter.Eq("_id", objectId);
            collection.DeleteOne(filter1);

            return RedirectToAction("MojiOglasi");

        }

        // POST: AutomobiliController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Pretrazi(IndexAutomobiliViewModel model)
        {
            var connectionString = "mongodb://localhost/?safe=true";
            var client = new MongoClient(connectionString);
            var db = client.GetDatabase("PolovniAutomobili");

            var collection = db.GetCollection<Automobil>("automobili");

            var filterBuilder = Builders<Automobil>.Filter;
            var filter = filterBuilder.Empty;
            if (model.Automobil.Marka != null)
                filter = filter & filterBuilder.Eq("Marka", model.Automobil.Marka);
            if (model.Automobil.Model != null)
                filter = filter & filterBuilder.Eq("Model", model.Automobil.Model);
            if (model.Automobil.Lokacija != null)
                filter = filter & filterBuilder.Eq("Lokacija", model.Automobil.Lokacija);
            if (model.Automobil.Cena != 0)
                filter = filter & filterBuilder.Lt("Cena", model.Automobil.Cena);
            if (model.Automobil.Godiste != 0)
                filter = filter & filterBuilder.Gt("Godiste", model.Automobil.Godiste);
            if (model.Automobil.Oznake[0] != null)
                filter = filter & filterBuilder.Eq("Oznake", model.Automobil.Oznake[0]);
            if (model.Automobil.Oznake[1] != null)
                filter = filter & filterBuilder.Eq("Oznake", model.Automobil.Oznake[1]);

            List<Automobil> kola = new List<Automobil>();
            foreach (Automobil a in collection.Find(filter).ToCursor().ToEnumerable())
            {
                kola.Add(a);
            }

            //model.Automobili = kola;
            //model.Automobil = null;
            IndexAutomobiliViewModel noviModel = new IndexAutomobiliViewModel
            {
                Automobili = kola
            };

            return View("Index", noviModel);
        }
    }
}

PolovniAutomobili-proba/PolovniAutomobili-proba/Views/Automobili/Create.cshtml
@model PolovniAutomobili_proba.Models.Automobil

@{
    ViewData["Title"] = "Dodaj oglas";
}
<div class="row">
    <div class="col-md-4">
        <section>
            <form asp-controller="Automobili" asp-action="Create" method="post">
                <h4>Dodaj novi oglas</h4>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="@Model.Marka"></label>
                    <input asp-for="@Model.Marka" class="form-control" />
                    <span asp-validation-for="@Model.Marka" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Model"></label>
                    <input asp-for="@Model.Model" class="form-control" />
                    <span asp-validation-for="@Model.Model" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Lokacija"></label>
                    <input asp-for="@Model.Lokacija" class="form-control" />
                    <span asp-validation-for="@Model.Lokacija" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Cena">Cena u €</label>
                    <input asp-for="@Model.Cena" class="form-control" />
                    <span asp-validation-for="@Model.Cena" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Godiste"></label>
                    <input asp-for="@Model.Godiste" class="form-control" />
                    <span asp-validation-for="@Model.Godiste" class="text-danger"></span>
                </div>

                @*deo za oznake*@

                <div class="form-group">
                    <label asp-for="@Model.Oznake">Karoserija</label>
                    <select asp-for="@Model.Oznake[0]" class="form-control">
                        <option value=""></option>
                        <option value="limuzina">Limuzina</option>
                        <option value="kupe">Kupe</option>
                        <option value="hečbek">Hečbek</option>
                        <option value="karavan">Karavan</option>
                        <option value="džip">Džip</option>
                        <option value="kombi">Kombi</option>
                        <option value="kamion">Kamion</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Oznake">Gorivo</label>
                    <select asp-for="@Model.Oznake[1]" class="form-control">
                        <option value=""></option>
                        <option value="benzin">Benzin</option>
                        <option value="dizel">Dizel</option>
                        <option value="autogas">Autogas</option>
                        <option value="električni">Električni</option>
                        <option value="hibrid">Hibrid</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Potvrdi</button>
                </div>
            </form>
        </section>
    </div>
</div>

PolovniAutomobili-proba/PolovniAutomobili-proba/Views/Automobili/Details.cshtml
@model PolovniAutomobili_proba.Models.Automobil
@{
    ViewData["Title"] = "Detalji o oglasu";
}

<h1>Detalji o oglasu</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marka)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marka)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Godiste)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Godiste)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cena)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cena)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Lokacija)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Lokacija)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Oznake)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.Oznake)
            {
                @item
                <label> </label>
            }
        </dd>
    </dl>
</div>
<div>
    <h4>Informacije o prodavcu</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.Ime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik.Prezime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.Prezime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik.KontaktTelefon)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.KontaktTelefon)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Automobili" asp-action="Index">Vrati se nazad</a>
</div>

PolovniAutomobili-proba/PolovniAutomobili-proba/Views/Automobili/Edit.cshtml
@model PolovniAutomobili_proba.Models.EditAutomobilViewModel

@{
    ViewData["Title"] = "Izmeni oglas";
}

<div class="row">
    <div class="col-md-4">
        <section>
            <form asp-controller="Automobili" asp-action="Edit" method="post">
                <h4>Izmeni oglas</h4>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    @*Html.HiddenFor(m => m.Id)*@
                    <input asp-for="@Model.AutoId class=" hidden form-control">
                </div>
                <div class="form-group">
                    @*@Html.HiddenFor(m => m.Korisnik)*@
                    <input asp-for="@Model.UserId class=" hidden form-control">
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Automobil.Marka"></label>
                    <input asp-for="@Model.Automobil.Marka" class="form-control" />
                    <span asp-validation-for="@Model.Automobil.Marka" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Automobil.Model"></label>
                    <input asp-for="@Model.Automobil.Model" class="form-control" />
                    <span asp-validation-for="@Model.Automobil.Model" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Automobil.Lokacija"></label>
                    <input asp-for="@Model.Automobil.Lokacija" class="form-control" />
                    <span asp-validation-for="@Model.Automobil.Lokacija" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Automobil.Cena">Cena u €</label>
                    <input asp-for="@Model.Automobil.Cena" class="form-control" />
                    <span asp-validation-for="@Model.Automobil.Cena" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Automobil.Godiste"></label>
                    <input asp-for="@Model.Automobil.Godiste" class="form-control" />
                    <span asp-validation-for="@Model.Automobil.Godiste" class="text-danger"></span>
                </div>

                @*deo za oznake*@

                <div class="form-group">
                    <label asp-for="@Model.Automobil.Oznake">Karoserija</label>
                    <select asp-for="@Model.Automobil.Oznake[0]" class="form-control">
                        <option value=""></option>
                        <option value="limuzina">Limuzina</option>
                        <option value="kupe">Kupe</option>
                        <option value="hečbek">Hečbek</option>
                        <option value="karavan">Karavan</option>
                        <option value="džip">Džip</option>
                        <option value="kombi">Kombi</option>
                        <option value="kamion">Kamion</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Automobil.Oznake">Gorivo</label>
                    <select asp-for="@Model.Automobil.Oznake[1]" class="form-control">
                        <option value=""></option>
                        <option value="benzin">Benzin</option>
                        <option value="dizel">Dizel</option>
                        <option value="autogas">Autogas</option>
                        <option value="električni">Električni</option>
                        <option value="hibrid">Hibrid</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Potvrdi</button>
                </div>
            </form>
        </section>
    </div>
</div>

PolovniAutomobili-proba/PolovniAutomobili-proba/Views/Automobili/Index.cshtml
@model PolovniAutomobili_proba.Models.IndexAutomobiliViewModel
@{
    ViewData["Title"] = "Oglasi";
}
<div>
    @Html.ActionLink("Dodaj oglas", "Create", "Automobili")
</div>


<br />

<div class="col-md-3">
    <form asp-controller="Automobili" asp-action="Pretrazi" method="post">
        <h4>Pretraži oglase</h4>
        <hr />
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group">
            <label asp-for="@Model.Automobil.Marka"></label>
            <input asp-for="@Model.Automobil.Marka" class="form-control" />
            <span asp-validation-for="@Model.Automobil.Marka" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Automobil.Model"></label>
            <input asp-for="@Model.Automobil.Model" class="form-control" />
            <span asp-validation-for="@Model.Automobil.Model" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Automobil.Lokacija"></label>
            <input asp-for="@Model.Automobil.Lokacija" class="form-control" />
            <span asp-validation-for="@Model.Automobil.Lokacija" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Automobil.Cena">Cena do (u €)</label>
            <input asp-for="@Model.Automobil.Cena" value="0" class="form-control" />
            <span asp-validation-for="@Model.Automobil.Cena" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Automobil.Godiste">Godiste od</label>
            <input asp-for="@Model.Automobil.Godiste" value="0" class="form-control" />
            <span asp-validation-for="@Model.Automobil.Godiste" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Automobil.Oznake">Karoserija</label>
            <select asp-for="@Model.Automobil.Oznake[0]" class="form-control">
                <option value=""></option>
                <option value="limuzina">Limuzina</option>
                <option value="kupe">Kupe</option>
                <option value="hečbek">Hečbek</option>
                <option value="karavan">Karavan</option>
                <option value="džip">Džip</option>
                <option value="kombi">Kombi</option>
                <option value="kamion">Kamion</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Automobil.Oznake">Gorivo</label>
            <select asp-for="@Model.Automobil.Oznake[1]" class="form-control">
                <option value=""></option>
                <option value="benzin">Benzin</option>
                <option value="dizel">Dizel</option>
                <option value="autogas">Autogas</option>
                <option value="električni">Električni</option>
                <option value="hibrid">Hibrid</option>
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Pretraži</button>
        </div>
    </form>
</div>

<br />

<h4 id="oglasi">Oglasi</h4>
<hr>
@if (Model.Automobili.Count() > 0)
{
    <div>
        <table class="table table-bordered">
            <tr class="table-success">
                <th>
                    Marka
                </th>
                <th>
                    Model
                </th>
                <th>
                    Godiste
                </th>
                <th>
                    Lokacija
                </th>
                <th>
                    Cena (€)
                </th>
                <th>
                    Kontakt prodavca
                </th>
                <th>

                </th>
            </tr>
            @foreach (var item in Model.Automobili)
            {
                <tr>
                    <td>
                        @item.Marka
                    </td>
                    <td>
                        @item.Model
                    </td>
                    <td>
                        @item.Godiste
                    </td>
                    <td>
                        @item.Lokacija
                    </td>
                    <td>
                        @item.Cena
                    </td>
                    <td>
                        @item.Korisnik.KontaktTelefon
                    </td>
                    <td>
                        @Html.ActionLink("Vidi detalje...", "Details", new { id = item.Id })
                    </td>
                </tr>
            }
        </table>
    </div>
}

PolovniAutomobili-proba/PolovniAutomobili-proba/Views/Automobili/MojiOglasi.cshtml
@model IEnumerable<PolovniAutomobili_proba.Models.Automobil>
@{
    ViewData["Title"] = "Moji oglasi";
}

<div>
    @Html.ActionLink("Dodaj oglas", "Create", "Automobili")
</div>

<br />

@if (Model.Count() > 0)
{
    <div>
        <table class="table table-bordered">
            <tr class="table-success">
                <th>
                    Marka
                </th>
                <th>
                    Model
                </th>
                <th>
                    Godiste
                </th>
                <th>
                    Lokacija
                </th>
                <th>
                    Cena (€)
                </th>
                <th>

                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Marka
                    </td>
                    <td>
                        @item.Model
                    </td>
                    <td>
                        @item.Godiste
                    </td>
                    <td>
                        @item.Lokacija
                    </td>
                    <td>
                        @item.Cena
                    </td>
                    <td>
                        @Html.ActionLink("Obriši", "Delete", new { id = item.Id }) | @Html.ActionLink("Izmeni", "Edit", new { id = item.Id }) | @Html.ActionLink("Detaljnije", "Details", new { id = item.Id })
                    </td>
                </tr>
            }
        </table>
    </div>
}

<div>
    <a asp-controller="Automobili" asp-action="Index">Vrati se nazad</a>
</div>